// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/Smart-Door-Lock-IoT/api/features/configuration/handlers"
	"github.com/Smart-Door-Lock-IoT/api/features/configuration/injector"
	"github.com/Smart-Door-Lock-IoT/api/features/configuration/repositories"
	"github.com/Smart-Door-Lock-IoT/api/features/configuration/services"
	"github.com/Smart-Door-Lock-IoT/api/pkg/database"
)

// Injectors from handlers.go:

func InitConfigurationHandlers() *injector.ConfigurationHandlers {
	db := database.New()
	config := repositories.NewConfig(db)
	pin := services.NewPin(config)
	handlersPin := handlers.NewPin(pin)
	configurationHandlers := injector.NewConfigurationHandlers(handlersPin)
	return configurationHandlers
}
